### ISSUE TITLE
When selecting multible videos they are added to the playlist in the wrong order

### ISSUE THREAD

**Issue by zefr0x** [zer0-x/cwitch#1]
# Expected behavior
Videos should be added to the mpv playlist from the oldest to the most recent, so you will start with watching the oldest video.

# Actual behavior
Videos are added from the most recent to the oldest, so you will start watching the most recent video rather then the oldest one.

**Comment by maitreyi14522** [comment]
Hi! im a first time contributor could you pls mention the source code that needs to be rectified

**Comment by zefr0x** [comment]
First, thank you for your interest in contributing.

It should be [here](https://github.com/zer0-x/cwitch/blob/ea7ed7dca7a457eca4493dedd3b4679faf09bc80/cwitch/cli.py#L134). This function will print info about the selected videos/streams, ask for a format, and add them to the playlist, then it will start MPV.

There is no problem with the text printed in the CLI (it is in the preferred order). It is just about the playlist order in MPV, so it would be better if you can find a way to play it in reverse (or add them in reverse) with the MPV api.
